export const USER_DATA_REQUEST = 'USER_DATA_REQUEST'
export const USER_DATA_RESPONSE = 'USER_DATA_RESPONSE'
export const USER_DATA_RESPONSE_FAIL = 'USER_DATA_RESPONSE_FAIL'

export const SET_LOCAL_CURRENCY_REQUEST = 'SET_LOCAL_CURRENCY_REQUEST'
export const SET_LOCAL_CURRENCY_RESPONSE = 'SET_LOCAL_CURRENCY_RESPONSE'
export const SET_LOCAL_CURRENCY_RESPONSE_FAIL = 'SET_LOCAL_CURRENCY_RESPONSE_FAIL'

export const SET_AMOUNT_CURRENCY = 'SET_AMOUNT_CURRENCY'
export const SET_AMOUNT_CURRENCY_CONVERTED = 'SET_AMOUNT_CURRENCY_CONVERTED'

export const SWAP_PANELS = 'SWAP_PANELS'

export const SET_CURRENCY_HISTORY_REQUEST = 'SET_CURRENCY_HISTORY_REQUEST'
export const SET_CURRENCY_HISTORY_DAILY_RESPONSE = 'SET_CURRENCY_HISTORY_DAILY_RESPONSE'
export const SET_CURRENCY_HISTORY_DAILY_RESPONSE_FAIL = 'SET_CURRENCY_HISTORY_DAILY_RESPONSE_FAIL'

export const CHANGE_THEME = 'CHANGE_THEME'
