export const URL_MY_IP = 'https://api.db-ip.com/v2/free/self'
export const URL_MY_POSITION = 'https://api.ipregistry.co/'
export const API_KEY_FOR_MY_POSITION = 'dusq3llhgq2s7hb3'
export const URL_GET_CURRENCIES = 'https://cdn.jsdelivr.net/gh/fawazahmed0/currency-api@1/latest/currencies.json'
export const URL_CONVERT_SELECT_CURRENCY = 'https://cdn.jsdelivr.net/gh/fawazahmed0/currency-api@1/latest/currencies/'
